# Write dogecoin.conf + RPC-CREDENTIALS.txt for a fresh install.
# Never uses a shared default password.
param(
  [Parameter(Mandatory = $true)][string]$DataDir,
  [Parameter(Mandatory = $true)][string]$RpcPassword,
  [string]$RpcUser = "gpenode",
  [ValidateSet("dump", "settlement", "core")]
  [string]$Profile = "dump",
  [string]$ExampleConf = "",
  [switch]$Force
)
$ErrorActionPreference = "Stop"

New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
$conf = Join-Path $DataDir "dogecoin.conf"
$cred = Join-Path $DataDir "RPC-CREDENTIALS.txt"
$utc = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

if ((Test-Path $conf) -and -not $Force) {
  Write-Host "CONF_EXISTS $conf"
  exit 0
}

if ($ExampleConf -and (Test-Path $ExampleConf) -and $Profile -ne "core") {
  $lines = Get-Content $ExampleConf
  $out = New-Object System.Collections.Generic.List[string]
  [void]$out.Add("# Generated by installer - unique credentials for THIS install only.")
  [void]$out.Add("# Created: $utc")
  $seenUser = $false
  $seenPass = $false
  foreach ($line in $lines) {
    if ($line -match '^\s*rpcuser\s*=') {
      [void]$out.Add("rpcuser=$RpcUser")
      $seenUser = $true
      continue
    }
    if ($line -match '^\s*rpcpassword\s*=') {
      [void]$out.Add("rpcpassword=$RpcPassword")
      $seenPass = $true
      continue
    }
    if ($line -match 'CHANGE_ME') { continue }
    [void]$out.Add($line)
  }
  if (-not $seenUser) { [void]$out.Add("rpcuser=$RpcUser") }
  if (-not $seenPass) { [void]$out.Add("rpcpassword=$RpcPassword") }
  $body = ($out -join "`n") + "`n"
} else {
  $extra = switch ($Profile) {
    "dump" {
      @"
prune=5500
dbcache=1024
maxmempool=50
maxconnections=32
disablewallet=1
printtoconsole=0
txindex=0
"@
    }
    "settlement" {
      @"
prune=0
dbcache=2048
maxmempool=100
maxconnections=40
disablewallet=0
printtoconsole=0
txindex=0
"@
    }
    default {
      @"
# Core GUI / general node
printtoconsole=0
"@
    }
  }
  $body = @"
# Generated by installer - unique credentials for THIS install only.
# Created: $utc
# Profile: $Profile

server=1
listen=1

rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcuser=$RpcUser
rpcpassword=$RpcPassword

$extra
"@
}

Set-Content -Path $conf -Value $body -Encoding UTF8

$credBody = @"
Dogecoin RPC credentials - THIS INSTALL ONLY
============================================
Generated: $utc
Data dir:  $DataDir
Conf file: $conf

rpcuser=$RpcUser
rpcpassword=$RpcPassword

RPC is bound to 127.0.0.1 by default.
Store this securely. You can delete this file after saving the password elsewhere.
Do not share this file. Do not commit it to git.
"@
Set-Content -Path $cred -Value $credBody -Encoding UTF8

Write-Host "CONF_OK $conf"
Write-Host "CRED_OK $cred"
