#!/usr/bin/env bash
# Bootstrap Dogecoin settlement node on Debian (gpednode1).
# Default datadir: Vultr File System at /mnt/gpenodestore/dogecoin
# Fallback: /var/lib/dogecoin if cloud FS not mounted yet.
set -euo pipefail

CLOUD_MNT="${CLOUD_MNT:-/mnt/gpenodestore}"
# virtiofs mount tag — set after Vultr attaches FS to this instance
VIRTIOFS_TAG="${VIRTIOFS_TAG:-}"
DOGE_USER="${DOGE_USER:-dogecoin}"
SERVICE_NAME="dogecoind"

export DEBIAN_FRONTEND=noninteractive

echo "==> packages"
apt-get update -qq
apt-get install -y -qq \
  ca-certificates curl wget gnupg xz-utils \
  build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 \
  libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev \
  libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev \
  libdb5.3++-dev libminiupnpc-dev libzmq3-dev \
  ufw fail2ban

echo "==> cloud filesystem mount"
mkdir -p "$CLOUD_MNT"
if ! mountpoint -q "$CLOUD_MNT"; then
  if [[ -n "$VIRTIOFS_TAG" ]]; then
    echo "Mounting virtiofs tag=$VIRTIOFS_TAG -> $CLOUD_MNT"
    mount -t virtiofs "$VIRTIOFS_TAG" "$CLOUD_MNT" || true
  fi
  # common Vultr paths after attach
  if ! mountpoint -q "$CLOUD_MNT"; then
    for tag in $(ls /dev/disk/by-id 2>/dev/null || true); do :; done
    # try fstab entry if present
    if grep -q gpenodestore /etc/fstab 2>/dev/null; then
      mount "$CLOUD_MNT" || true
    fi
  fi
fi

if mountpoint -q "$CLOUD_MNT"; then
  DATADIR="$CLOUD_MNT/dogecoin"
  echo "Using CLOUD datadir: $DATADIR"
else
  DATADIR="/var/lib/dogecoin"
  echo "WARNING: cloud FS not mounted. Using local $DATADIR"
  echo "Attach gpenodestore1 to this instance in Vultr, then re-run with VIRTIOFS_TAG=..."
fi

mkdir -p "$DATADIR"
if ! id "$DOGE_USER" &>/dev/null; then
  useradd --system --home-dir "$DATADIR" --shell /usr/sbin/nologin "$DOGE_USER"
fi
chown -R "$DOGE_USER:$DOGE_USER" "$DATADIR"
if mountpoint -q "$CLOUD_MNT"; then
  chown -R "$DOGE_USER:$DOGE_USER" "$CLOUD_MNT" || true
fi

CONF="$DATADIR/dogecoin.conf"
if [[ ! -f "$CONF" ]]; then
  RPCUSER="gpe_$(openssl rand -hex 4)"
  RPCPASS="$(openssl rand -hex 24)"
  cat >"$CONF" <<EOF
# Generated by bootstrap_settlement.sh
listen=1
server=1
txindex=0
prune=2200
dbcache=256
maxmempool=50
maxconnections=40
# testnet=1
rpcuser=${RPCUSER}
rpcpassword=${RPCPASS}
rpcallowip=127.0.0.1
rpcbind=127.0.0.1
printtoconsole=0
EOF
  chown "$DOGE_USER:$DOGE_USER" "$CONF"
  chmod 600 "$CONF"
  echo "Wrote $CONF (rpc credentials random; stored only on server)"
fi

# Persist mount if virtiofs tag known
if [[ -n "$VIRTIOFS_TAG" ]] && ! grep -q "$CLOUD_MNT" /etc/fstab 2>/dev/null; then
  echo "${VIRTIOFS_TAG} ${CLOUD_MNT} virtiofs defaults,_netdev 0 0" >> /etc/fstab
  echo "Added fstab entry for ${CLOUD_MNT}"
fi

# Symlink convenience
mkdir -p /etc/dogecoin
ln -sfn "$DATADIR" /etc/dogecoin/datadir
echo "$DATADIR" > /etc/dogecoin/datadir.path

echo "==> firewall (SSH + Dogecoin P2P; RPC stays local)"
ufw allow OpenSSH || true
ufw allow 22556/tcp comment 'dogecoin mainnet p2p' || true
ufw allow 44556/tcp comment 'dogecoin testnet p2p' || true
ufw --force enable || true

echo "==> bootstrap base done"
echo "DATADIR=$DATADIR"
echo "Next: install dogecoind binary or build, then systemd unit."
df -h "$CLOUD_MNT" 2>/dev/null || df -h /
